* Что это?

  Универсальная кириллическая(если быть точным: ru/ua/by) раскладка для X-ов. Особенностью является то, что знаки пунктуации находятся на тех же клавишах, что и в английской (us).

* Зачем?

  Чтобы при наборе знаков пунктуации не задумываться про текущую раскладку.

  Минусы:
  1. некоторые символы прихошлось перетащить на 3 уровень, для русского языка пришлось пожертвовать «юэщжёцйъ».
  2. как следствие их достаточно тяжело набирать одной рукой. Как воркэраунд можно включить режим sticky modifiers.
  3. раскладка немного отличается от «йцукен».

  Кандидаты на перенос «наверх» тщательно выбирались из соображений минимальной частотности использования и как можно меньшей разницы с «йцукен». Раскладки для украинского/белорусского языков для меня вторичны, так что дополнительные символы из них тоже на третьем уровне.

* Использование

** Инсталляция

   #+BEGIN_SRC sh
     cd /path/to/repo/dir
     git clone https://github.com/a13/xkb-custom.git
     ln -sf `pwd`/xkb-custom ~/.xkb
   #+END_SRC

** Настройка X-ов

   Чтобы не приходилось лезть в системные файлы (которые всё равно перезаписываются при обновлении), приходится использовать такой костыль в автозагрузке(например в ~/.xsession):

   #+BEGIN_SRC sh
     # сброс старых настроек
     setxkbmap us -option
     # минимальный вариант (главное - забидить клавишу-модификатор для 3 уровня).
     setxkbmap us,rup -option "lv3:menu_switch" -print | xkbcomp -I"$HOME/.xkb" - "$DISPLAY"
   #+END_SRC

   Все возможные(в базовой) варианты выбора модификаторов можно посмотреть командой

   #+BEGIN_SRC sh
     grep lv3: /usr/share/X11/xkb/rules/base.lst
   #+END_SRC


** Настройка Emacs (при необходимости):

   например так:

   #+BEGIN_SRC emacs-lisp
     (add-to-list 'load-path "~/.xkb/contrib")
     (require 'unipunct)
   #+END_SRC

   или автоматически с помощью Quelpa (использование ~master~ из чужого репозитория в общем случае небезопасно, возможно лучше указывать конкретный хэш)

   #+BEGIN_SRC emacs-lisp
     (use-package unipunct
       :quelpa
       (unipunct
        :url "https://raw.githubusercontent.com/a13/xkb-custom/master/contrib/unipunct.el"
        :fetcher url))
   #+END_SRC

   После этого для использования будет доступен метод ввода "russian-unipunct" (главное не забыть установить ~default-input-method~ или активировать с помощью [[https://github.com/a13/reverse-im.el][reverse-im]]).

** Схема раскладки


   #+BEGIN_EXAMPLE
     +----------------------------------------------------------------+
     | 1! | 2@ | 3# | 4$ | 5% | 6^ | 7& | 8* | 9( | 0) | -_ | =+ | ’~ |
     +----------------------------------------------------------------+
       |хХїЇ| бБ |уУюЮ| кК |еЕэЭ| нН |гГґҐ|шШщЩ | жЖ |зЗєЄ| [{ | }] |
       +------------------------------------------------------------+
        | фФ |ыЫіІ|вВўЎ| аА | пП | рР |оОёЁ| лЛ | дД | ;: | '" | \| |
        +-----------------------------------------------------------+
            |яЯѣѢ|чЧцЦ| сС | мМ |иИйЙ| тТ |ьЬъЪ| ,< | .> | /? |
            +-------------------------------------------------+
   #+END_EXAMPLE

* TODO

  - [ ] Literate the sources
  - [ ] Generate all layouts(xkb/emacs) from one source
  - [ ] Support other OSes
